#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cRepositorio.LINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Libreria")]
	public partial class ModeloDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCLIENTE(CLIENTE instance);
    partial void UpdateCLIENTE(CLIENTE instance);
    partial void DeleteCLIENTE(CLIENTE instance);
    partial void InsertCOMPRAS_CLIENTE(COMPRAS_CLIENTE instance);
    partial void UpdateCOMPRAS_CLIENTE(COMPRAS_CLIENTE instance);
    partial void DeleteCOMPRAS_CLIENTE(COMPRAS_CLIENTE instance);
    partial void InsertEDITORIAL_MARCA_SELLO(EDITORIAL_MARCA_SELLO instance);
    partial void UpdateEDITORIAL_MARCA_SELLO(EDITORIAL_MARCA_SELLO instance);
    partial void DeleteEDITORIAL_MARCA_SELLO(EDITORIAL_MARCA_SELLO instance);
    partial void InsertFACTURAVENTA(FACTURAVENTA instance);
    partial void UpdateFACTURAVENTA(FACTURAVENTA instance);
    partial void DeleteFACTURAVENTA(FACTURAVENTA instance);
    partial void InsertINVENTARIO(INVENTARIO instance);
    partial void UpdateINVENTARIO(INVENTARIO instance);
    partial void DeleteINVENTARIO(INVENTARIO instance);
    partial void InsertPRODUCTO(PRODUCTO instance);
    partial void UpdatePRODUCTO(PRODUCTO instance);
    partial void DeletePRODUCTO(PRODUCTO instance);
    partial void InsertPROMOCION(PROMOCION instance);
    partial void UpdatePROMOCION(PROMOCION instance);
    partial void DeletePROMOCION(PROMOCION instance);
    partial void InsertTIPO(TIPO instance);
    partial void UpdateTIPO(TIPO instance);
    partial void DeleteTIPO(TIPO instance);
    #endregion
		
		public ModeloDataContext() : 
				base(global::cRepositorio.Properties.Settings.Default.LibreriaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CLIENTE> CLIENTE
		{
			get
			{
				return this.GetTable<CLIENTE>();
			}
		}
		
		public System.Data.Linq.Table<COMPRAS_CLIENTE> COMPRAS_CLIENTE
		{
			get
			{
				return this.GetTable<COMPRAS_CLIENTE>();
			}
		}
		
		public System.Data.Linq.Table<EDIMARCASELLO_TIPO> EDIMARCASELLO_TIPO
		{
			get
			{
				return this.GetTable<EDIMARCASELLO_TIPO>();
			}
		}
		
		public System.Data.Linq.Table<EDITORIAL_MARCA_SELLO> EDITORIAL_MARCA_SELLO
		{
			get
			{
				return this.GetTable<EDITORIAL_MARCA_SELLO>();
			}
		}
		
		public System.Data.Linq.Table<FACTURA_PRODUCTO> FACTURA_PRODUCTO
		{
			get
			{
				return this.GetTable<FACTURA_PRODUCTO>();
			}
		}
		
		public System.Data.Linq.Table<FACTURAVENTA> FACTURAVENTA
		{
			get
			{
				return this.GetTable<FACTURAVENTA>();
			}
		}
		
		public System.Data.Linq.Table<INVENTARIO> INVENTARIO
		{
			get
			{
				return this.GetTable<INVENTARIO>();
			}
		}
		
		public System.Data.Linq.Table<PRODUCTO> PRODUCTO
		{
			get
			{
				return this.GetTable<PRODUCTO>();
			}
		}
		
		public System.Data.Linq.Table<PROMOCION> PROMOCION
		{
			get
			{
				return this.GetTable<PROMOCION>();
			}
		}
		
		public System.Data.Linq.Table<TIPO> TIPO
		{
			get
			{
				return this.GetTable<TIPO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLIENTE")]
	public partial class CLIENTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDENTCLIENTE;
		
		private string _NOMBRE;
		
		private string _PRIAPELLIDO;
		
		private string _SEGAPELLIDO;
		
		private string _TELEFONO;
		
		private string _DIRECCION;
		
		private EntitySet<COMPRAS_CLIENTE> _COMPRAS_CLIENTE;
		
		private EntitySet<FACTURAVENTA> _FACTURAVENTA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDENTCLIENTEChanging(int value);
    partial void OnIDENTCLIENTEChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnPRIAPELLIDOChanging(string value);
    partial void OnPRIAPELLIDOChanged();
    partial void OnSEGAPELLIDOChanging(string value);
    partial void OnSEGAPELLIDOChanged();
    partial void OnTELEFONOChanging(string value);
    partial void OnTELEFONOChanged();
    partial void OnDIRECCIONChanging(string value);
    partial void OnDIRECCIONChanged();
    #endregion
		
		public CLIENTE()
		{
			this._COMPRAS_CLIENTE = new EntitySet<COMPRAS_CLIENTE>(new Action<COMPRAS_CLIENTE>(this.attach_COMPRAS_CLIENTE), new Action<COMPRAS_CLIENTE>(this.detach_COMPRAS_CLIENTE));
			this._FACTURAVENTA = new EntitySet<FACTURAVENTA>(new Action<FACTURAVENTA>(this.attach_FACTURAVENTA), new Action<FACTURAVENTA>(this.detach_FACTURAVENTA));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDENTCLIENTE", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDENTCLIENTE
		{
			get
			{
				return this._IDENTCLIENTE;
			}
			set
			{
				if ((this._IDENTCLIENTE != value))
				{
					this.OnIDENTCLIENTEChanging(value);
					this.SendPropertyChanging();
					this._IDENTCLIENTE = value;
					this.SendPropertyChanged("IDENTCLIENTE");
					this.OnIDENTCLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIAPELLIDO", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string PRIAPELLIDO
		{
			get
			{
				return this._PRIAPELLIDO;
			}
			set
			{
				if ((this._PRIAPELLIDO != value))
				{
					this.OnPRIAPELLIDOChanging(value);
					this.SendPropertyChanging();
					this._PRIAPELLIDO = value;
					this.SendPropertyChanged("PRIAPELLIDO");
					this.OnPRIAPELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEGAPELLIDO", DbType="VarChar(100)")]
		public string SEGAPELLIDO
		{
			get
			{
				return this._SEGAPELLIDO;
			}
			set
			{
				if ((this._SEGAPELLIDO != value))
				{
					this.OnSEGAPELLIDOChanging(value);
					this.SendPropertyChanging();
					this._SEGAPELLIDO = value;
					this.SendPropertyChanged("SEGAPELLIDO");
					this.OnSEGAPELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this.OnTELEFONOChanging(value);
					this.SendPropertyChanging();
					this._TELEFONO = value;
					this.SendPropertyChanged("TELEFONO");
					this.OnTELEFONOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this.OnDIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._DIRECCION = value;
					this.SendPropertyChanged("DIRECCION");
					this.OnDIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTE_COMPRAS_CLIENTE", Storage="_COMPRAS_CLIENTE", ThisKey="IDENTCLIENTE", OtherKey="IDENTCLIENTE")]
		public EntitySet<COMPRAS_CLIENTE> COMPRAS_CLIENTE
		{
			get
			{
				return this._COMPRAS_CLIENTE;
			}
			set
			{
				this._COMPRAS_CLIENTE.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTE_FACTURAVENTA", Storage="_FACTURAVENTA", ThisKey="IDENTCLIENTE", OtherKey="IDENTCLIENTE")]
		public EntitySet<FACTURAVENTA> FACTURAVENTA
		{
			get
			{
				return this._FACTURAVENTA;
			}
			set
			{
				this._FACTURAVENTA.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_COMPRAS_CLIENTE(COMPRAS_CLIENTE entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTE = this;
		}
		
		private void detach_COMPRAS_CLIENTE(COMPRAS_CLIENTE entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTE = null;
		}
		
		private void attach_FACTURAVENTA(FACTURAVENTA entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTE = this;
		}
		
		private void detach_FACTURAVENTA(FACTURAVENTA entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COMPRAS_CLIENTE")]
	public partial class COMPRAS_CLIENTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDREGISTROCLIENTE;
		
		private int _IDENTCLIENTE;
		
		private int _CANTIDADCOMPRAS;
		
		private EntityRef<CLIENTE> _CLIENTE;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDREGISTROCLIENTEChanging(int value);
    partial void OnIDREGISTROCLIENTEChanged();
    partial void OnIDENTCLIENTEChanging(int value);
    partial void OnIDENTCLIENTEChanged();
    partial void OnCANTIDADCOMPRASChanging(int value);
    partial void OnCANTIDADCOMPRASChanged();
    #endregion
		
		public COMPRAS_CLIENTE()
		{
			this._CLIENTE = default(EntityRef<CLIENTE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDREGISTROCLIENTE", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDREGISTROCLIENTE
		{
			get
			{
				return this._IDREGISTROCLIENTE;
			}
			set
			{
				if ((this._IDREGISTROCLIENTE != value))
				{
					this.OnIDREGISTROCLIENTEChanging(value);
					this.SendPropertyChanging();
					this._IDREGISTROCLIENTE = value;
					this.SendPropertyChanged("IDREGISTROCLIENTE");
					this.OnIDREGISTROCLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDENTCLIENTE", DbType="Int NOT NULL")]
		public int IDENTCLIENTE
		{
			get
			{
				return this._IDENTCLIENTE;
			}
			set
			{
				if ((this._IDENTCLIENTE != value))
				{
					if (this._CLIENTE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDENTCLIENTEChanging(value);
					this.SendPropertyChanging();
					this._IDENTCLIENTE = value;
					this.SendPropertyChanged("IDENTCLIENTE");
					this.OnIDENTCLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANTIDADCOMPRAS", DbType="Int NOT NULL")]
		public int CANTIDADCOMPRAS
		{
			get
			{
				return this._CANTIDADCOMPRAS;
			}
			set
			{
				if ((this._CANTIDADCOMPRAS != value))
				{
					this.OnCANTIDADCOMPRASChanging(value);
					this.SendPropertyChanging();
					this._CANTIDADCOMPRAS = value;
					this.SendPropertyChanged("CANTIDADCOMPRAS");
					this.OnCANTIDADCOMPRASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTE_COMPRAS_CLIENTE", Storage="_CLIENTE", ThisKey="IDENTCLIENTE", OtherKey="IDENTCLIENTE", IsForeignKey=true)]
		public CLIENTE CLIENTE
		{
			get
			{
				return this._CLIENTE.Entity;
			}
			set
			{
				CLIENTE previousValue = this._CLIENTE.Entity;
				if (((previousValue != value) 
							|| (this._CLIENTE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CLIENTE.Entity = null;
						previousValue.COMPRAS_CLIENTE.Remove(this);
					}
					this._CLIENTE.Entity = value;
					if ((value != null))
					{
						value.COMPRAS_CLIENTE.Add(this);
						this._IDENTCLIENTE = value.IDENTCLIENTE;
					}
					else
					{
						this._IDENTCLIENTE = default(int);
					}
					this.SendPropertyChanged("CLIENTE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EDIMARCASELLO_TIPO")]
	public partial class EDIMARCASELLO_TIPO
	{
		
		private int _IDEDSEMA;
		
		private int _IDTIPO;
		
		public EDIMARCASELLO_TIPO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDEDSEMA", DbType="Int NOT NULL")]
		public int IDEDSEMA
		{
			get
			{
				return this._IDEDSEMA;
			}
			set
			{
				if ((this._IDEDSEMA != value))
				{
					this._IDEDSEMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTIPO", DbType="Int NOT NULL")]
		public int IDTIPO
		{
			get
			{
				return this._IDTIPO;
			}
			set
			{
				if ((this._IDTIPO != value))
				{
					this._IDTIPO = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EDITORIAL_MARCA_SELLO")]
	public partial class EDITORIAL_MARCA_SELLO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDEDSEMA;
		
		private string _NOMBRE;
		
		private EntitySet<PRODUCTO> _PRODUCTO;
		
		private EntitySet<PROMOCION> _PROMOCION;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDEDSEMAChanging(int value);
    partial void OnIDEDSEMAChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    #endregion
		
		public EDITORIAL_MARCA_SELLO()
		{
			this._PRODUCTO = new EntitySet<PRODUCTO>(new Action<PRODUCTO>(this.attach_PRODUCTO), new Action<PRODUCTO>(this.detach_PRODUCTO));
			this._PROMOCION = new EntitySet<PROMOCION>(new Action<PROMOCION>(this.attach_PROMOCION), new Action<PROMOCION>(this.detach_PROMOCION));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDEDSEMA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDEDSEMA
		{
			get
			{
				return this._IDEDSEMA;
			}
			set
			{
				if ((this._IDEDSEMA != value))
				{
					this.OnIDEDSEMAChanging(value);
					this.SendPropertyChanging();
					this._IDEDSEMA = value;
					this.SendPropertyChanged("IDEDSEMA");
					this.OnIDEDSEMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EDITORIAL_MARCA_SELLO_PRODUCTO", Storage="_PRODUCTO", ThisKey="IDEDSEMA", OtherKey="IDEDSEMA")]
		public EntitySet<PRODUCTO> PRODUCTO
		{
			get
			{
				return this._PRODUCTO;
			}
			set
			{
				this._PRODUCTO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EDITORIAL_MARCA_SELLO_PROMOCION", Storage="_PROMOCION", ThisKey="IDEDSEMA", OtherKey="IDEDSEMA")]
		public EntitySet<PROMOCION> PROMOCION
		{
			get
			{
				return this._PROMOCION;
			}
			set
			{
				this._PROMOCION.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PRODUCTO(PRODUCTO entity)
		{
			this.SendPropertyChanging();
			entity.EDITORIAL_MARCA_SELLO = this;
		}
		
		private void detach_PRODUCTO(PRODUCTO entity)
		{
			this.SendPropertyChanging();
			entity.EDITORIAL_MARCA_SELLO = null;
		}
		
		private void attach_PROMOCION(PROMOCION entity)
		{
			this.SendPropertyChanging();
			entity.EDITORIAL_MARCA_SELLO = this;
		}
		
		private void detach_PROMOCION(PROMOCION entity)
		{
			this.SendPropertyChanging();
			entity.EDITORIAL_MARCA_SELLO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FACTURA_PRODUCTO")]
	public partial class FACTURA_PRODUCTO
	{
		
		private int _NUMEROFACTURA;
		
		private int _IDPRODUCTO;
		
		private int _CANTIDAD;
		
		public FACTURA_PRODUCTO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMEROFACTURA", DbType="Int NOT NULL")]
		public int NUMEROFACTURA
		{
			get
			{
				return this._NUMEROFACTURA;
			}
			set
			{
				if ((this._NUMEROFACTURA != value))
				{
					this._NUMEROFACTURA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPRODUCTO", DbType="Int NOT NULL")]
		public int IDPRODUCTO
		{
			get
			{
				return this._IDPRODUCTO;
			}
			set
			{
				if ((this._IDPRODUCTO != value))
				{
					this._IDPRODUCTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANTIDAD", DbType="Int NOT NULL")]
		public int CANTIDAD
		{
			get
			{
				return this._CANTIDAD;
			}
			set
			{
				if ((this._CANTIDAD != value))
				{
					this._CANTIDAD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FACTURAVENTA")]
	public partial class FACTURAVENTA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NUMEROFACTURA;
		
		private int _IDENTCLIENTE;
		
		private decimal _COSTOTOTAL;
		
		private System.DateTime _FECHAFACTURA;
		
		private EntityRef<CLIENTE> _CLIENTE;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNUMEROFACTURAChanging(int value);
    partial void OnNUMEROFACTURAChanged();
    partial void OnIDENTCLIENTEChanging(int value);
    partial void OnIDENTCLIENTEChanged();
    partial void OnCOSTOTOTALChanging(decimal value);
    partial void OnCOSTOTOTALChanged();
    partial void OnFECHAFACTURAChanging(System.DateTime value);
    partial void OnFECHAFACTURAChanged();
    #endregion
		
		public FACTURAVENTA()
		{
			this._CLIENTE = default(EntityRef<CLIENTE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMEROFACTURA", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int NUMEROFACTURA
		{
			get
			{
				return this._NUMEROFACTURA;
			}
			set
			{
				if ((this._NUMEROFACTURA != value))
				{
					this.OnNUMEROFACTURAChanging(value);
					this.SendPropertyChanging();
					this._NUMEROFACTURA = value;
					this.SendPropertyChanged("NUMEROFACTURA");
					this.OnNUMEROFACTURAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDENTCLIENTE", DbType="Int NOT NULL")]
		public int IDENTCLIENTE
		{
			get
			{
				return this._IDENTCLIENTE;
			}
			set
			{
				if ((this._IDENTCLIENTE != value))
				{
					if (this._CLIENTE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDENTCLIENTEChanging(value);
					this.SendPropertyChanging();
					this._IDENTCLIENTE = value;
					this.SendPropertyChanged("IDENTCLIENTE");
					this.OnIDENTCLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COSTOTOTAL", DbType="Decimal(18,0) NOT NULL")]
		public decimal COSTOTOTAL
		{
			get
			{
				return this._COSTOTOTAL;
			}
			set
			{
				if ((this._COSTOTOTAL != value))
				{
					this.OnCOSTOTOTALChanging(value);
					this.SendPropertyChanging();
					this._COSTOTOTAL = value;
					this.SendPropertyChanged("COSTOTOTAL");
					this.OnCOSTOTOTALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHAFACTURA", DbType="Date NOT NULL")]
		public System.DateTime FECHAFACTURA
		{
			get
			{
				return this._FECHAFACTURA;
			}
			set
			{
				if ((this._FECHAFACTURA != value))
				{
					this.OnFECHAFACTURAChanging(value);
					this.SendPropertyChanging();
					this._FECHAFACTURA = value;
					this.SendPropertyChanged("FECHAFACTURA");
					this.OnFECHAFACTURAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTE_FACTURAVENTA", Storage="_CLIENTE", ThisKey="IDENTCLIENTE", OtherKey="IDENTCLIENTE", IsForeignKey=true)]
		public CLIENTE CLIENTE
		{
			get
			{
				return this._CLIENTE.Entity;
			}
			set
			{
				CLIENTE previousValue = this._CLIENTE.Entity;
				if (((previousValue != value) 
							|| (this._CLIENTE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CLIENTE.Entity = null;
						previousValue.FACTURAVENTA.Remove(this);
					}
					this._CLIENTE.Entity = value;
					if ((value != null))
					{
						value.FACTURAVENTA.Add(this);
						this._IDENTCLIENTE = value.IDENTCLIENTE;
					}
					else
					{
						this._IDENTCLIENTE = default(int);
					}
					this.SendPropertyChanged("CLIENTE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.INVENTARIO")]
	public partial class INVENTARIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _IDPRODUCTO;
		
		private int _CANTIDAD;
		
		private EntityRef<PRODUCTO> _PRODUCTO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnIDPRODUCTOChanging(int value);
    partial void OnIDPRODUCTOChanged();
    partial void OnCANTIDADChanging(int value);
    partial void OnCANTIDADChanged();
    #endregion
		
		public INVENTARIO()
		{
			this._PRODUCTO = default(EntityRef<PRODUCTO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPRODUCTO", DbType="Int NOT NULL")]
		public int IDPRODUCTO
		{
			get
			{
				return this._IDPRODUCTO;
			}
			set
			{
				if ((this._IDPRODUCTO != value))
				{
					if (this._PRODUCTO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDPRODUCTOChanging(value);
					this.SendPropertyChanging();
					this._IDPRODUCTO = value;
					this.SendPropertyChanged("IDPRODUCTO");
					this.OnIDPRODUCTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANTIDAD", DbType="Int NOT NULL")]
		public int CANTIDAD
		{
			get
			{
				return this._CANTIDAD;
			}
			set
			{
				if ((this._CANTIDAD != value))
				{
					this.OnCANTIDADChanging(value);
					this.SendPropertyChanging();
					this._CANTIDAD = value;
					this.SendPropertyChanged("CANTIDAD");
					this.OnCANTIDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRODUCTO_INVENTARIO", Storage="_PRODUCTO", ThisKey="IDPRODUCTO", OtherKey="IDPRODUCTO", IsForeignKey=true)]
		public PRODUCTO PRODUCTO
		{
			get
			{
				return this._PRODUCTO.Entity;
			}
			set
			{
				PRODUCTO previousValue = this._PRODUCTO.Entity;
				if (((previousValue != value) 
							|| (this._PRODUCTO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PRODUCTO.Entity = null;
						previousValue.INVENTARIO.Remove(this);
					}
					this._PRODUCTO.Entity = value;
					if ((value != null))
					{
						value.INVENTARIO.Add(this);
						this._IDPRODUCTO = value.IDPRODUCTO;
					}
					else
					{
						this._IDPRODUCTO = default(int);
					}
					this.SendPropertyChanged("PRODUCTO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRODUCTO")]
	public partial class PRODUCTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDPRODUCTO;
		
		private string _NOMBRE;
		
		private string _AUTOR;
		
		private int _IDTIPO;
		
		private decimal _PRECIO;
		
		private System.DateTime _FECHAPUBLICACION;
		
		private int _IDEDSEMA;
		
		private EntitySet<INVENTARIO> _INVENTARIO;
		
		private EntityRef<EDITORIAL_MARCA_SELLO> _EDITORIAL_MARCA_SELLO;
		
		private EntityRef<TIPO> _TIPO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPRODUCTOChanging(int value);
    partial void OnIDPRODUCTOChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnAUTORChanging(string value);
    partial void OnAUTORChanged();
    partial void OnIDTIPOChanging(int value);
    partial void OnIDTIPOChanged();
    partial void OnPRECIOChanging(decimal value);
    partial void OnPRECIOChanged();
    partial void OnFECHAPUBLICACIONChanging(System.DateTime value);
    partial void OnFECHAPUBLICACIONChanged();
    partial void OnIDEDSEMAChanging(int value);
    partial void OnIDEDSEMAChanged();
    #endregion
		
		public PRODUCTO()
		{
			this._INVENTARIO = new EntitySet<INVENTARIO>(new Action<INVENTARIO>(this.attach_INVENTARIO), new Action<INVENTARIO>(this.detach_INVENTARIO));
			this._EDITORIAL_MARCA_SELLO = default(EntityRef<EDITORIAL_MARCA_SELLO>);
			this._TIPO = default(EntityRef<TIPO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPRODUCTO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDPRODUCTO
		{
			get
			{
				return this._IDPRODUCTO;
			}
			set
			{
				if ((this._IDPRODUCTO != value))
				{
					this.OnIDPRODUCTOChanging(value);
					this.SendPropertyChanging();
					this._IDPRODUCTO = value;
					this.SendPropertyChanged("IDPRODUCTO");
					this.OnIDPRODUCTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUTOR", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string AUTOR
		{
			get
			{
				return this._AUTOR;
			}
			set
			{
				if ((this._AUTOR != value))
				{
					this.OnAUTORChanging(value);
					this.SendPropertyChanging();
					this._AUTOR = value;
					this.SendPropertyChanged("AUTOR");
					this.OnAUTORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTIPO", DbType="Int NOT NULL")]
		public int IDTIPO
		{
			get
			{
				return this._IDTIPO;
			}
			set
			{
				if ((this._IDTIPO != value))
				{
					if (this._TIPO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTIPOChanging(value);
					this.SendPropertyChanging();
					this._IDTIPO = value;
					this.SendPropertyChanged("IDTIPO");
					this.OnIDTIPOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO", DbType="Decimal(18,0) NOT NULL")]
		public decimal PRECIO
		{
			get
			{
				return this._PRECIO;
			}
			set
			{
				if ((this._PRECIO != value))
				{
					this.OnPRECIOChanging(value);
					this.SendPropertyChanging();
					this._PRECIO = value;
					this.SendPropertyChanged("PRECIO");
					this.OnPRECIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHAPUBLICACION", DbType="Date NOT NULL")]
		public System.DateTime FECHAPUBLICACION
		{
			get
			{
				return this._FECHAPUBLICACION;
			}
			set
			{
				if ((this._FECHAPUBLICACION != value))
				{
					this.OnFECHAPUBLICACIONChanging(value);
					this.SendPropertyChanging();
					this._FECHAPUBLICACION = value;
					this.SendPropertyChanged("FECHAPUBLICACION");
					this.OnFECHAPUBLICACIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDEDSEMA", DbType="Int NOT NULL")]
		public int IDEDSEMA
		{
			get
			{
				return this._IDEDSEMA;
			}
			set
			{
				if ((this._IDEDSEMA != value))
				{
					if (this._EDITORIAL_MARCA_SELLO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDEDSEMAChanging(value);
					this.SendPropertyChanging();
					this._IDEDSEMA = value;
					this.SendPropertyChanged("IDEDSEMA");
					this.OnIDEDSEMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRODUCTO_INVENTARIO", Storage="_INVENTARIO", ThisKey="IDPRODUCTO", OtherKey="IDPRODUCTO")]
		public EntitySet<INVENTARIO> INVENTARIO
		{
			get
			{
				return this._INVENTARIO;
			}
			set
			{
				this._INVENTARIO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EDITORIAL_MARCA_SELLO_PRODUCTO", Storage="_EDITORIAL_MARCA_SELLO", ThisKey="IDEDSEMA", OtherKey="IDEDSEMA", IsForeignKey=true)]
		public EDITORIAL_MARCA_SELLO EDITORIAL_MARCA_SELLO
		{
			get
			{
				return this._EDITORIAL_MARCA_SELLO.Entity;
			}
			set
			{
				EDITORIAL_MARCA_SELLO previousValue = this._EDITORIAL_MARCA_SELLO.Entity;
				if (((previousValue != value) 
							|| (this._EDITORIAL_MARCA_SELLO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EDITORIAL_MARCA_SELLO.Entity = null;
						previousValue.PRODUCTO.Remove(this);
					}
					this._EDITORIAL_MARCA_SELLO.Entity = value;
					if ((value != null))
					{
						value.PRODUCTO.Add(this);
						this._IDEDSEMA = value.IDEDSEMA;
					}
					else
					{
						this._IDEDSEMA = default(int);
					}
					this.SendPropertyChanged("EDITORIAL_MARCA_SELLO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TIPO_PRODUCTO", Storage="_TIPO", ThisKey="IDTIPO", OtherKey="IDTIPO", IsForeignKey=true)]
		public TIPO TIPO
		{
			get
			{
				return this._TIPO.Entity;
			}
			set
			{
				TIPO previousValue = this._TIPO.Entity;
				if (((previousValue != value) 
							|| (this._TIPO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TIPO.Entity = null;
						previousValue.PRODUCTO.Remove(this);
					}
					this._TIPO.Entity = value;
					if ((value != null))
					{
						value.PRODUCTO.Add(this);
						this._IDTIPO = value.IDTIPO;
					}
					else
					{
						this._IDTIPO = default(int);
					}
					this.SendPropertyChanged("TIPO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_INVENTARIO(INVENTARIO entity)
		{
			this.SendPropertyChanging();
			entity.PRODUCTO = this;
		}
		
		private void detach_INVENTARIO(INVENTARIO entity)
		{
			this.SendPropertyChanging();
			entity.PRODUCTO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PROMOCION")]
	public partial class PROMOCION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDPROMO;
		
		private int _IDTIPO;
		
		private int _IDEDSEMA;
		
		private System.DateTime _FECHAINICIO;
		
		private System.DateTime _FECHAFIN;
		
		private int _DESCUENTO;
		
		private bool _ESTADO;
		
		private EntityRef<EDITORIAL_MARCA_SELLO> _EDITORIAL_MARCA_SELLO;
		
		private EntityRef<TIPO> _TIPO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPROMOChanging(int value);
    partial void OnIDPROMOChanged();
    partial void OnIDTIPOChanging(int value);
    partial void OnIDTIPOChanged();
    partial void OnIDEDSEMAChanging(int value);
    partial void OnIDEDSEMAChanged();
    partial void OnFECHAINICIOChanging(System.DateTime value);
    partial void OnFECHAINICIOChanged();
    partial void OnFECHAFINChanging(System.DateTime value);
    partial void OnFECHAFINChanged();
    partial void OnDESCUENTOChanging(int value);
    partial void OnDESCUENTOChanged();
    partial void OnESTADOChanging(bool value);
    partial void OnESTADOChanged();
    #endregion
		
		public PROMOCION()
		{
			this._EDITORIAL_MARCA_SELLO = default(EntityRef<EDITORIAL_MARCA_SELLO>);
			this._TIPO = default(EntityRef<TIPO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPROMO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDPROMO
		{
			get
			{
				return this._IDPROMO;
			}
			set
			{
				if ((this._IDPROMO != value))
				{
					this.OnIDPROMOChanging(value);
					this.SendPropertyChanging();
					this._IDPROMO = value;
					this.SendPropertyChanged("IDPROMO");
					this.OnIDPROMOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTIPO", DbType="Int NOT NULL")]
		public int IDTIPO
		{
			get
			{
				return this._IDTIPO;
			}
			set
			{
				if ((this._IDTIPO != value))
				{
					if (this._TIPO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTIPOChanging(value);
					this.SendPropertyChanging();
					this._IDTIPO = value;
					this.SendPropertyChanged("IDTIPO");
					this.OnIDTIPOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDEDSEMA", DbType="Int NOT NULL")]
		public int IDEDSEMA
		{
			get
			{
				return this._IDEDSEMA;
			}
			set
			{
				if ((this._IDEDSEMA != value))
				{
					if (this._EDITORIAL_MARCA_SELLO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDEDSEMAChanging(value);
					this.SendPropertyChanging();
					this._IDEDSEMA = value;
					this.SendPropertyChanged("IDEDSEMA");
					this.OnIDEDSEMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHAINICIO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHAINICIO
		{
			get
			{
				return this._FECHAINICIO;
			}
			set
			{
				if ((this._FECHAINICIO != value))
				{
					this.OnFECHAINICIOChanging(value);
					this.SendPropertyChanging();
					this._FECHAINICIO = value;
					this.SendPropertyChanged("FECHAINICIO");
					this.OnFECHAINICIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHAFIN", DbType="DateTime NOT NULL")]
		public System.DateTime FECHAFIN
		{
			get
			{
				return this._FECHAFIN;
			}
			set
			{
				if ((this._FECHAFIN != value))
				{
					this.OnFECHAFINChanging(value);
					this.SendPropertyChanging();
					this._FECHAFIN = value;
					this.SendPropertyChanged("FECHAFIN");
					this.OnFECHAFINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCUENTO", DbType="Int NOT NULL")]
		public int DESCUENTO
		{
			get
			{
				return this._DESCUENTO;
			}
			set
			{
				if ((this._DESCUENTO != value))
				{
					this.OnDESCUENTOChanging(value);
					this.SendPropertyChanging();
					this._DESCUENTO = value;
					this.SendPropertyChanged("DESCUENTO");
					this.OnDESCUENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Bit NOT NULL")]
		public bool ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this.OnESTADOChanging(value);
					this.SendPropertyChanging();
					this._ESTADO = value;
					this.SendPropertyChanged("ESTADO");
					this.OnESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EDITORIAL_MARCA_SELLO_PROMOCION", Storage="_EDITORIAL_MARCA_SELLO", ThisKey="IDEDSEMA", OtherKey="IDEDSEMA", IsForeignKey=true)]
		public EDITORIAL_MARCA_SELLO EDITORIAL_MARCA_SELLO
		{
			get
			{
				return this._EDITORIAL_MARCA_SELLO.Entity;
			}
			set
			{
				EDITORIAL_MARCA_SELLO previousValue = this._EDITORIAL_MARCA_SELLO.Entity;
				if (((previousValue != value) 
							|| (this._EDITORIAL_MARCA_SELLO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EDITORIAL_MARCA_SELLO.Entity = null;
						previousValue.PROMOCION.Remove(this);
					}
					this._EDITORIAL_MARCA_SELLO.Entity = value;
					if ((value != null))
					{
						value.PROMOCION.Add(this);
						this._IDEDSEMA = value.IDEDSEMA;
					}
					else
					{
						this._IDEDSEMA = default(int);
					}
					this.SendPropertyChanged("EDITORIAL_MARCA_SELLO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TIPO_PROMOCION", Storage="_TIPO", ThisKey="IDTIPO", OtherKey="IDTIPO", IsForeignKey=true)]
		public TIPO TIPO
		{
			get
			{
				return this._TIPO.Entity;
			}
			set
			{
				TIPO previousValue = this._TIPO.Entity;
				if (((previousValue != value) 
							|| (this._TIPO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TIPO.Entity = null;
						previousValue.PROMOCION.Remove(this);
					}
					this._TIPO.Entity = value;
					if ((value != null))
					{
						value.PROMOCION.Add(this);
						this._IDTIPO = value.IDTIPO;
					}
					else
					{
						this._IDTIPO = default(int);
					}
					this.SendPropertyChanged("TIPO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TIPO")]
	public partial class TIPO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDTIPO;
		
		private string _NOMBRE;
		
		private EntitySet<PRODUCTO> _PRODUCTO;
		
		private EntitySet<PROMOCION> _PROMOCION;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTIPOChanging(int value);
    partial void OnIDTIPOChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    #endregion
		
		public TIPO()
		{
			this._PRODUCTO = new EntitySet<PRODUCTO>(new Action<PRODUCTO>(this.attach_PRODUCTO), new Action<PRODUCTO>(this.detach_PRODUCTO));
			this._PROMOCION = new EntitySet<PROMOCION>(new Action<PROMOCION>(this.attach_PROMOCION), new Action<PROMOCION>(this.detach_PROMOCION));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTIPO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDTIPO
		{
			get
			{
				return this._IDTIPO;
			}
			set
			{
				if ((this._IDTIPO != value))
				{
					this.OnIDTIPOChanging(value);
					this.SendPropertyChanging();
					this._IDTIPO = value;
					this.SendPropertyChanged("IDTIPO");
					this.OnIDTIPOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TIPO_PRODUCTO", Storage="_PRODUCTO", ThisKey="IDTIPO", OtherKey="IDTIPO")]
		public EntitySet<PRODUCTO> PRODUCTO
		{
			get
			{
				return this._PRODUCTO;
			}
			set
			{
				this._PRODUCTO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TIPO_PROMOCION", Storage="_PROMOCION", ThisKey="IDTIPO", OtherKey="IDTIPO")]
		public EntitySet<PROMOCION> PROMOCION
		{
			get
			{
				return this._PROMOCION;
			}
			set
			{
				this._PROMOCION.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PRODUCTO(PRODUCTO entity)
		{
			this.SendPropertyChanging();
			entity.TIPO = this;
		}
		
		private void detach_PRODUCTO(PRODUCTO entity)
		{
			this.SendPropertyChanging();
			entity.TIPO = null;
		}
		
		private void attach_PROMOCION(PROMOCION entity)
		{
			this.SendPropertyChanging();
			entity.TIPO = this;
		}
		
		private void detach_PROMOCION(PROMOCION entity)
		{
			this.SendPropertyChanging();
			entity.TIPO = null;
		}
	}
}
#pragma warning restore 1591
